language: python

python:
  - "3.5"

addons:
  apt:
    packages:
    - sshpass

install:
  - pip install numpy
  - pip install pandas
  - pip install cmmnbuild_dep_manager
  - sshpass -e ssh -N -D 1080 opsw@lxplus.cern.ch
  - export HTTP_PROXY="socks5://localhost:1080/"
  - export HTTPS_PROXY="socks5://localhost:1080/"
  - pip install -e .

script:
  - pytest tests
