language: python

python:
  - "3.5"

addons:
  apt:
    packages:
    - sshpass

install:
  - pip install --upgrade urllib3
  - pip install --upgrade requests
  - pip install --upgrade requests[socks]
  - pip install pytest
  - pip install .
  - python .travis-setup-jars.py
  - which java
  - find /home/travis/virtualenv/python3.5.2/lib/python3.5/

script:
  - pytest tests
