language: python

python:
  - "3.5"

addons:
  apt:
    packages:
    - sshpass
    - openjdk-8-jdk

env:
  - JAVA_JVM_LIB="/usr/lib/jvm/java-7-oracle/jre/lib/amd64/server/libjvm.so"

install:
  - pip install --upgrade urllib3
  - pip install --upgrade requests
  - pip install --upgrade requests[socks]
  - pip install pytest
  - pip install .
  - python .travis-setup-jars.py

script:
  - pytest tests
