language: python

python:
  - "3.5"

addons:
  apt:
    packages:
    - sshpass

install:
  - pip install numpy
  - pip install pandas
  - pip install requests[socks]
  - pip install cmmnbuild_dep_manager
  - sshpass -e ssh -oStrictHostKeyChecking=no -N -D 51080 opsw@lxplus.cern.ch &
  - sleep 5
  - export HTTP_PROXY="socks5://localhost:51080/"
  - export HTTPS_PROXY="socks5://localhost:51080/"
  - pip install -e .
  - python -m cmmnbuild_dep_manager resolve
  - killall ssh sshpass

script:
  - pytest tests
