language: python

python:
  - "3.5"

addons:
  apt:
    packages:
    - openjdk-8-jdk

env:
  - JAVA_JVM_LIB="/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/libjvm.so"

install:
  - pip install pytest
  - pip install git+https://gitlab.cern.ch/mihostet/cmmnbuild-dep-manager.git
  - pip install .

script:
  - pytest tests
